version: "3.7"

networks:
  web:
    external: true

services:
  app:
    image: ghcr.io/chaostreff-flensburg/digital-signage:latest
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.saas.rule=Host(`saas.ctfl.space`)"
      - "traefik.http.routers.saas.entrypoints=https,http"
      - "traefik.http.services.saas.loadbalancer.server.port=80"
      - "traefik.http.routers.saas.tls.certresolver=mytlschallenge"
      - "traefik.docker.network=web"
